package com.github.dappermickie.runepouch.loadout.names;

import net.runelite.api.gameval.SpriteID;
import java.util.List;
import java.util.stream.Collectors;

public class RunepouchLoadoutIcon {
  public int spriteId;
  public String name;

  public RunepouchLoadoutIcon(int spriteId, String name) {
    this.spriteId = spriteId;
    this.name = name;
  }

  public static List<RunepouchLoadoutIcon> getIcons(String search) {
    if (search.isEmpty()) {
      return ICONS;
    }

    return ICONS.stream()
      .filter(icon -> icon.name.toLowerCase().contains(search.toLowerCase()))
      .collect(Collectors.toList());
  }

  public static final List<RunepouchLoadoutIcon> ICONS = List.of(
    new RunepouchLoadoutIcon(SpriteID.AccManIcons._6, "Default"),

    new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_STRIKE, "Wind Strike"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_STRIKE, "Water Strike"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_STRIKE, "Earth Strike"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_STRIKE, "Fire Strike"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_BOLT, "Wind Bolt"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_BOLT, "Water Bolt"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_BOLT, "Earth Bolt"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_BOLT, "Fire Bolt"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_BLAST, "Wind Blast"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_BLAST, "Water Blast"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_BLAST, "Earth Blast"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_BLAST, "Fire Blast"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WIND_WAVE, "Wind Wave"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WATER_WAVE, "Water Wave"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.EARTH_WAVE, "Earth Wave"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.FIRE_WAVE, "Fire Wave"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.WIND_SURGE, "Wind Surge"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.WATER_SURGE, "Water Surge"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.EARTH_SURGE, "Earth Surge"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.FIRE_SURGE, "Fire Surge"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.IBAN_BLAST, "Iban Blast"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.CHARGE, "Charge"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.FLAMES_OF_ZAMORAK, "Flames of Zamorak"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CLAWS_OF_GUTHIX, "Claws of Guthix"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.SARADOMIN_STRIKE, "Saradomin Strike"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CRUMBLE_UNDEAD, "Crumble Undead"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.BIND, "Bind"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SNARE, "Snare"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.ENTANGLE, "Entangle"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LUMBRIDGE_TELEPORT, "Lumbridge Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.FALADOR_TELEPORT, "Falador Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.VARROCK_TELEPORT, "Varrock Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CAMELOT_TELEPORT, "Camelot Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.ARDOUGNE_TELEPORT, "Ardougne Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WATCHTOWER_TELEPORT, "Watchtower Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TROLLHEIM_TELEPORT, "Trollheim Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_HOUSE, "Teleport to House"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.LUMBRIDGE_HOME_TELEPORT, "Lumbridge Home Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_APE_ATOLL, "Teleport to Ape Atoll"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_KOUREND, "Teleport to Kourend"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.CIVITAS_ILLA_FORTIS_TELEPORT, "Civitas Ila Fortis Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELE_BLOCK, "Tele Block"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.TELEKINETIC_GRAB, "Telekinetic Grab"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_LUMBRIDGE, "Teleother Lumbridge"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_FALADOR, "Teleother Falador"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_CAMELOT, "Teleother Camelot"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_BOUNTY_TARGET, "Teleport to Bounty Target"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CONFUSE, "Confuse"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.WEAKEN, "Weaken"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CURSE, "Curse"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.ENFEEBLE, "Enfeeble"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.STUN, "Stun"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.VULNERABILITY, "Vulnerability"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LOW_LEVEL_ALCHEMY, "Low Level Alchemy"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.HIGH_LEVEL_ALCHEMY, "High Level Alchemy"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.SUPERHEAT_ITEM, "Superheat Item"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_1_ENCHANT, "Lvl 1 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_2_ENCHANT, "Lvl 2 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_3_ENCHANT, "Lvl 3 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_4_ENCHANT, "Lvl 4 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.LVL_5_ENCHANT, "Lvl 5 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.LVL_6_ENCHANT, "Lvl 6 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.LVL_7_ENCHANT, "Lvl 7 Enchant"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, "Enchant Crossbow Bolt"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_WATER_ORB, "Charge Water Orb"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_EARTH_ORB, "Charge Earth Orb"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_FIRE_ORB, "Charge Fire Orb"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CHARGE_AIR_ORB, "Charge Air Orb"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.BONES_TO_BANANAS, "Bones to Bananas"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.BONES_TO_PEACHES, "Bones to Peaches"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.MAGIC_DART, "Magic Dart"),

    new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_RUSH, "Ice Rush"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BURST, "Ice Burst"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BLITZ, "Ice Blitz"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.ICE_BARRAGE, "Ice Barrage"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_RUSH, "Smoke Rush"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BURST, "Smoke Burst"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BLITZ, "Smoke Blitz"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BARRAGE, "Smoke Barrage"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_RUSH, "Blood Rush"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BURST, "Blood Burst"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BLITZ, "Blood Blitz"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BARRAGE, "Blood Barrage"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_RUSH, "Shadow Rush"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BURST, "Shadow Burst"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BLITZ, "Shadow Blitz"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BARRAGE, "Shadow Barrage"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.PADDEWWA_TELEPORT, "Paddewwa Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.SENNTISTEN_TELEPORT, "Senntisten Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.KHARYRLL_TELEPORT, "Kharyll Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.LASSAR_TELEPORT, "Lassar Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.DAREEYAK_TELEPORT, "Dareeyak Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.CARRALLANGAR_TELEPORT, "Carrallangar Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.ANNAKARL_TELEPORT, "Annakarl Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon2.GHORROCK_TELEPORT, "Ghorrock Teleport"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.CALL_ANIMAL, "Call Animal"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.RAISE_SKELETON, "Raise Skeleton"),
    new RunepouchLoadoutIcon(SpriteID.Magicon.SUMMON_DEMON, "Summon Demon"),

    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BAKE_PIE, "Bake Pie"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SUPERGLASS_MAKE, "Superglass Make"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STRING_JEWELLERY, "String Jewellery"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.RECHARGE_DRAGONSTONE, "Recharge Dragonstone"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TAN_LEATHER, "Tan Leather"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SPIN_FLAX, "Spin Flax"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.PLANK_MAKE, "Plank Make"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MAGIC_IMBUE, "Magic Imbue"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.FERTILE_SOIL, "Fertile Soil"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_PLANT, "Cure Plant"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.GEOMANCY, "Geomancy"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HUMIDIFY, "Humidify"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BOW_AND_ARROW, "Bow and Arrow"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.NPC_CONTACT, "NPC Contact"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BOOST_POTION_SHARE, "Boost Potion Share"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STAT_RESTORE_POT_SHARE, "Stat Restore Pot Share"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.ENERGY_TRANSFER, "Energy Transfer"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE, "Vengeance"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE_OTHER, "Vengeance Other"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_ME, "Cure Me"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_GROUP, "Cure Group"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_OTHER, "Cure Other"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_GROUP, "Heal Group"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_OTHER, "Heal Other"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MOONCLAN_TELEPORT, "Moonclan Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.WATERBIRTH_TELEPORT, "Waterbirth Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.BARBARIAN_TELEPORT, "Barbarian Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.KHAZARD_TELEPORT, "Khazard Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.FISHING_GUILD_TELEPORT, "Fishing Guild Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.CATHERBY_TELEPORT, "Catherby Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.ICE_PLATEAU_TELEPORT, "Ice Plateau Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_MOONCLAN, "Tele Group Moonclan"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_WATERBIRTH, "Tele Group Waterbirth"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_BARBARIAN, "Tele Group Barbarian"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_KHAZARD, "Tele Group Khazard"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_FISHING_GUILD, "Tele Group Fishing Guild"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_CATHERBY, "Tele Group Catherby"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.TELE_GROUP_ICE_PLATEAU, "Tele Group Ice Plateau"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.OURANIA_TELEPORT, "Ourania Teleport"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.STAT_SPY, "Stat Spy"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.MONSTER_EXAMINE, "Monster Examine"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.HUNTER_KIT, "Hunter Kit"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.DREAM, "Dream"),
    new RunepouchLoadoutIcon(SpriteID.LunarMagicOn.SPELLBOOK_SWAP, "Spellbook Swap"),

    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_LESSER_GHOST, "Resurrect Lesser Ghost"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._24, "Resurrect Lesser Skeleton"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._25, "Resurrect Lesser Zombie"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._44, "Resurrect Superior Ghost (_44)"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_SUPERIOR_SKELETON, "Resurrect Superior Skeleton"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._48, "Resurrect Superior Zombie (_48)"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._45, "Resurrect Greater Ghost (_45)"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn._47, "Resurrect Greater Skeleton (_47)"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_GREATER_ZOMBIE, "Resurrect Greater Zombie"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.ADEPT_REANIMATION, "Adept Reanimation"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.BASIC_REANIMATION, "Basic Reanimation"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.EXPERT_REANIMATION, "Expert Reanimation"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MASTER_REANIMATION, "Master Reanimation"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.ARCEUUS_LIBRARY_TELEPORT, "Arceuus Library Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DRAYNOR_MANOR_TELEPORT, "Draynor Manor Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SALVE_GRAVEYARD_TELEPORT, "Salve Graveyard Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MIND_ALTAR_TELEPORT, "Mind Altar Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESPAWN_TELEPORT, "Respawn Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.FENKENSTRAINS_CASTLE_TELEPORT, "Fenkenstrain's Castle Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.WEST_ARDOUGNE_TELEPORT, "West Ardougne Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.HARMONY_ISLAND_TELEPORT, "Harmony Island Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.BARROWS_TELEPORT, "Barrows Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.APE_ATOLL_TELEPORT, "Ape Atoll Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.CEMETERY_TELEPORT, "Cemetery Teleport"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_CROPS, "Resurrect Crops"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.GHOSTLY_GRASP, "Ghostly Grasp"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SKELETAL_GRASP, "Skeletal Grasp"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.UNDEAD_GRASP, "Undead Grasp"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.INFERIOR_DEMONBANE, "Inferior Demonbane"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SUPERIOR_DEMONBANE, "Superior Demonbane"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_DEMONBANE, "Dark Demonbane"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.MARK_OF_DARKNESS, "Mark of Darkness"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.WARD_OF_ARCEUUS, "Ward of Arceuus"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.LESSER_CORRUPTION, "Lesser Corruption"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.GREATER_CORRUPTION, "Greater Corruption"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEATH_CHARGE, "Death Charge"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEMONIC_OFFERING, "Demonic Offering"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SINISTER_OFFERING, "Sinister Offering"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.SHADOW_VEIL, "Shadow Veil"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_LURE, "Dark Lure"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.VILE_VIGOUR, "Vile Vigour"),
    new RunepouchLoadoutIcon(SpriteID.MagicNecroOn.DEGRIME, "Degrime"),

    new RunepouchLoadoutIcon(SpriteID.SideIcons.MAGIC, "Spellbook Standard"),
    new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ANCIENT_MAGICKS, "Spellbook Ancient"),
    new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_LUNAR, "Spellbook Lunar"),
    new RunepouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ARCEUUS, "Spellbook Arceuus"),

    new RunepouchLoadoutIcon(SpriteID.Prayeron.THICK_SKIN, "Thick Skin"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.BURST_OF_STRENGTH, "Burst of Strength"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.CLARITY_OF_THOUGHT, "Clarity of Thought"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.ROCK_SKIN, "Rock Skin"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.SUPERHUMAN_STRENGTH, "Superhuman Strength"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.IMPROVED_REFLEXES, "Improved Reflexes"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.RAPID_RESTORE, "Rapid Restore"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.RAPID_HEAL, "Rapid Heal"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_ITEM, "Protect Item"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.STEEL_SKIN, "Steel Skin"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.ULTIMATE_STRENGTH, "Ultimate Strength"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.INCREDIBLE_REFLEXES, "Incredible Reflexes"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MAGIC, "Protect From Magic"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MISSILES, "Protect From Missiles"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MELEE, "Protect From Melee"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.REDEMPTION, "Redemption"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.RETRIBUTION, "Retribution"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.SMITE, "Smite"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.SHARP_EYE, "Sharp Eye"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_WILL, "Mystic Will"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.HAWK_EYE, "Hawk Eye"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_LORE, "Mystic Lore"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.EAGLE_EYE, "Eagle Eye"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_MIGHT, "Mystic Might"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_SUMMONING, "Protect From Summoning"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.CHIVALRY, "Chivalry"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PIETY, "Piety"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.PRESERVE, "Preserve"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.RIGOUR, "Rigour"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.AUGURY, "Augury"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.DEADEYE, "Deadeye"),
    new RunepouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_VIGOUR, "Mystic Vigour"),

    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_STRENGTH, "Ancient Strength"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_SIGHT, "Ancient Sight"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_WILL, "Ancient Will"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.TRINITAS, "Trinitas"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DECIMATE, "Decimate"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANNIHILATE, "Annihilate"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VAPORISE, "Vaporise"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_MELEE, "Dampen Melee"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_RANGED, "Dampen Ranged"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DAMPEN_MAGIC, "Dampen Magic"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.PURGE, "Purge"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REJUVENATION, "Rejuvenation"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.RUINOUS_GRACE, "Ruinous Grace"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.WRATH, "Wrath"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.METABOLISE, "Metabolise"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.BERSERKER, "Berserker"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.FUMUS_VOW, "Fumus Vow"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.CRUORS_VOW, "Cruors Vow"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.UMBRAS_VOW, "Umbras Vow"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.GLACIES_VOW, "Glacies Vow"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.INTENSIFY, "Intensify"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REBUKE, "Rebuke"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VINDICATION, "Vindication"),
    new RunepouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.PROTECT_ITEM, "Protect Item"),

    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ABYSSAL_SIRE, "Abyssal Sire"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ALCHEMICAL_HYDRA, "Alchemical Hydra"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.AMOXLIATL, "Amoxliatl"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_HUEYCOATL, "The Hueycoatl"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ROYAL_TITANS, "Royal Titans"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.YAMA, "Yama"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DOOM_OF_MOKHAIOTL, "Doom of Mokhaiotl"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.MIMIC, "Mimic"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.OBOR, "Obor"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ARAXXOR, "Araxxor"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BRYOPHYTA, "Bryophyta"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GIANT_MOLE, "Giant Mole"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GROTESQUE_GUARDIANS, "Grotesque Guardians"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TEMPOROSS, "Tempoross"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.WINTERTODT, "Wintertodt"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BARROWS_CHESTS, "Barrows Chests"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SARACHNIS, "Sarachnis"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KALPHITE_QUEEN, "Kalphite Queen"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.HESPORI, "Hespori"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SKOTIZO, "Skotizo"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ZALCANO, "Zalcano"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KING_BLACK_DRAGON, "King Black Dragon"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KRAKEN, "Kraken"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THERMONUCLEAR_SMOKE_DEVIL, "Thermonuclear Smoke Devil"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_GAUNTLET, "The Gauntlet"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ZULRAH, "Zulrah"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CERBERUS, "Cerberus"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.VORKATH, "Vorkath"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.GENERAL_GRAARDOR, "General Graardor"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KRIL_TSUTSAROTH, "Kril Tsutsaroth"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.COMMANDER_ZILYANA, "Commander Zilyana"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.KREEARRA, "Kree'arra"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.NIGHTMARE, "Nightmare"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CORPOREAL_BEAST, "Corporeal Beast"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC, "Chambers of Xeric"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THEATRE_OF_BLOOD, "Theatre of Blood"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.NEX, "Nex"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_SUPREME, "Dagannoth Supreme"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_REX, "Dagannoth Rex"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_PRIME, "Dagannoth Prime"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_CORRUPTED_GAUNTLET, "The Corrupted Gauntlet"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC_CHALLENGE_MODE, "Chambers of Xeric Challenge Mode"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT, "Tombs of Amascut"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT_EXPERT, "Tombs of Amascut Expert"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.PHANTOM_MUSPAH, "Phantom Muspah"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_ELEMENTAL, "Chaos Elemental"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.ARTIO_CALLISTO, "Artio Callisto"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CALVARION_VETION, "Calvarion Vetion"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SPINDEL_VENENATIS, "Spindel Venenatis"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_FANATIC, "Chaos Fanatic"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.CRAZY_ARCHAEOLOGIST, "Crazy Archaeologist"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DERANGED_ARCHAEOLOGIST, "Deranged Archaeologist"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SCORPIA, "Scorpia"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TZTOK_JAD, "TzTok Jad"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.TZKAL_ZUK, "TzKal Zuk"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_WHISPERER, "The Whisperer"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.DUKE_SUCELLUS, "Duke Sucellus"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.THE_LEVIATHAN, "The Leviathan"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.VARDORVIS, "Vardorvis"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SCURRIUS, "Scurrius"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SOL_HEREDIT, "Sol Heredit"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.LUNAR_CHESTS, "Lunar Chests"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.MAGGOT_KING, "Maggot King"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.SHELLBANE_GRYPHON, "Shellbane Gryphon"),
    new RunepouchLoadoutIcon(SpriteID.IconBoss25x25.BRUTUS, "Brutus"),

    new RunepouchLoadoutIcon(SpriteID.Staticons.ATTACK, "Attack"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.STRENGTH, "Strength"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.DEFENCE, "Defence"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.RANGED, "Ranged"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.PRAYER, "Prayer"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.MAGIC, "Magic"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.HITPOINTS, "Hitpoints"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.AGILITY, "Agility"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.HERBLORE, "Herblore"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.THIEVING, "Thieving"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.CRAFTING, "Crafting"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.FLETCHING, "Fletching"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.MINING, "Mining"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.SMITHING, "Smithing"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.FISHING, "Fishing"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.COOKING, "Cooking"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.FIREMAKING, "Firemaking"),
    new RunepouchLoadoutIcon(SpriteID.Staticons.WOODCUTTING, "Woodcutting"),
    new RunepouchLoadoutIcon(SpriteID.Staticons2.RUNECRAFT, "Runecraft"),
    new RunepouchLoadoutIcon(SpriteID.Staticons2.CONSTRUCTION, "Construction"),
    new RunepouchLoadoutIcon(SpriteID.Staticons2.FARMING, "Farming"),
    new RunepouchLoadoutIcon(SpriteID.Staticons2.HUNTER, "Hunter"),
    new RunepouchLoadoutIcon(SpriteID.Staticons2.SLAYER, "Slayer"),
    new RunepouchLoadoutIcon(SpriteID.Staticons2.SAILING, "Sailing"),

    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._0, "Clan Rank 0"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._1, "Clan Rank 1"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._2, "Clan Rank 2"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._3, "Clan Rank 3"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._4, "Clan Rank 4"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._5, "Clan Rank 5"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._6, "Clan Rank 6"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._7, "Clan Rank 7"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._8, "Clan Rank 8"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._9, "Clan Rank 9"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._10, "Clan Rank 10"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._11, "Clan Rank 11"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._12, "Clan Rank 12"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._13, "Clan Rank 13"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._14, "Clan Rank 14"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._15, "Clan Rank 15"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._16, "Clan Rank 16"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._17, "Clan Rank 17"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._18, "Clan Rank 18"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._19, "Clan Rank 19"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._20, "Clan Rank 20"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._21, "Clan Rank 21"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._22, "Clan Rank 22"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._23, "Clan Rank 23"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._24, "Clan Rank 24"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._25, "Clan Rank 25"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._26, "Clan Rank 26"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._27, "Clan Rank 27"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._28, "Clan Rank 28"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._29, "Clan Rank 29"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._30, "Clan Rank 30"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._31, "Clan Rank 31"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._32, "Clan Rank 32"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._33, "Clan Rank 33"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._34, "Clan Rank 34"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._35, "Clan Rank 35"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._36, "Clan Rank 36"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._37, "Clan Rank 37"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._38, "Clan Rank 38"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._39, "Clan Rank 39"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._40, "Clan Rank 40"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._41, "Clan Rank 41"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._42, "Clan Rank 42"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._43, "Clan Rank 43"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._44, "Clan Rank 44"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._45, "Clan Rank 45"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._46, "Clan Rank 46"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._47, "Clan Rank 47"),
    new RunepouchLoadoutIcon(SpriteID.ClanRankIcons._48, "Clan Rank 48"),

    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._0, "PK Skull"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._1, "TzHaar Fight Pit Skull"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._2, "High Risk Skull"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._3, "Forinthry Surge Skull"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._7, "Loot Keys Skull 0"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._8, "Loot Keys Skull 1"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._9, "Loot Keys Skull 2"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._10, "Loot Keys Skull 3"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._11, "Loot Keys Skull 4"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._12, "Loot Keys Skull 5"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._14, "Forinthry Loot Keys Skull 0"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._15, "Forinthry Loot Keys Skull 1"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._16, "Forinthry Loot Keys Skull 2"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._17, "Forinthry Loot Keys Skull 3"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._18, "Forinthry Loot Keys Skull 4"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._19, "Forinthry Loot Keys Skull 5"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._21, "Bounty Hunter Risk 1"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._22, "Bounty Hunter Risk 2"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._23, "Bounty Hunter Risk 3"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._24, "Bounty Hunter Risk 4"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._25, "Bounty Hunter Risk 5"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._28, "Skulled Bounty Hunter Risk 1"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._29, "Skulled Bounty Hunter Risk 2"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._30, "Skulled Bounty Hunter Risk 3"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._31, "Skulled Bounty Hunter Risk 4"),
    new RunepouchLoadoutIcon(SpriteID.HeadiconsPkInterface._32, "Skulled Bounty Hunter Risk 5"),

    new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._0, "Combat Achievement Rank 1"),
    new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._1, "Combat Achievement Rank 2"),
    new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._2, "Combat Achievement Rank 3"),
    new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._3, "Combat Achievement Rank 4"),
    new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._4, "Combat Achievement Rank 5"),
    new RunepouchLoadoutIcon(SpriteID.CaTierSwordsSmall._5, "Combat Achievement Rank 6"),

    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._0, "Rank Bronze"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._1, "Rank Iron"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._2, "Rank Steel"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._3, "Rank Mithril"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._4, "Rank Adamant"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._5, "Rank Rune"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._6, "Rank Dragon"),
    new RunepouchLoadoutIcon(SpriteID.PvpaRankicons._7, "Rank Master")
  );
}
